### ISSUE TITLE
parse2: improve error message on unexpected exception/interrupt task bind

### ISSUE THREAD

**Issue by tmplt** [japaric/rtfm-syntax#46]
On 4ba916d7faf75ca5ce706ff77b5be7af24d90a28, I want to parse out the interrupts/exceptions bound to hardware tasks. But running the below MWE (append to `src/tests/single.rs`) yields a panic with `Error("unexpected argument")`.
```rust
#[test]
fn parsing_binds() {
    let (app, _analysis) = crate::parse2(
        quote!(),
        quote!(
            mod app {
                #[task(binds = UART0)]
                fn foo(_: foo::Context) {}
            }
        ),
        Settings::default(),
    )
    .unwrap();
}
```
From the above, I expect to be able to find `UART0` in `app.hardware_tasks` after parsing.

@AfoHT  suspects https://github.com/rtic-rs/rtic-syntax/blob/fb8325208bf876b8ffe3804bd25e1a649e77d733/src/parse/app.rs#L117 from the empty `quote!()`, but the error persists if `quote!(parse_binds)` is passed instead. Parsing passes as expected if `binds = UART0` is omitted.

**Comment by perlindgren** [comment]
Not sure here, there is some peripherals default setting, without that the device peripherals are not forwarded, maybe the parser checks for that.

**Comment by tmplt** [comment]
Setting `parse_binds = true` in the `Settings` struct resolves the issue (credit to @AfoHT). Perhaps this should be reflected in the error message? An arm that checks the settings (if it's in scope) could be added.

**Comment by perlindgren** [comment]
`parse_binds` is active as a consequence of `peripherals = true` (which is now the default in RTIC 6). Its very rare that we don't use any bindings to interrupts.

**Comment by perlindgren** [comment]
But when used as a library it might not be that obvious. @tmplt feel free to PR with suggested improvements for using `rtic-syntax` as a library.

**Comment by AfoHT** [comment]
`parse_binds` is explicitly set in the default call to rtic-syntax, but adding such an error message should not be too hard, and @tmplt you are invited to make it happen, have a look in `src/parse/app.rs:253` :+1:
