### ISSUE TITLE
unused struct field

### ISSUE THREAD

**Issue by japaric** [japaric/rtfm-syntax#54]
`Analysis.tasks` appears to not be used by `cortex-m-rtic-macros` so it can probably be removed
https://github.com/rtic-rs/rtic-syntax/blob/b5389b4b72fc36ab5cfb0449037c51b9764c8d3a/src/analyze.rs#L325-L326

**Comment by AfoHT** [comment]
This tasklist is related to https://github.com/rtic-rs/cortex-m-rtic/issues/292, and previously before @korken89 did some thorough cleanup in https://github.com/rtic-rs/cortex-m-rtic/issues/292 it was used like this:

```
    // Get the list of all tasks
    // Currently unused, might be useful
    let task_list = analysis.tasks.clone();

    let mut tasks = vec![];
    if !task_list.is_empty() {
        tasks.push(quote!(
            enum Tasks {
                #(#task_list),*
            }
        ));
    }
```
And finally made available
```
        /// Unused
        #(#tasks)*
```

I sadly do not recall the general opinion, but @mabezdev seem(ed) very keen on having this available.

**Comment by MabezDev** [comment]
I've managed without it, not a huge deal if its removed now :)
